dist: xenial
language: python
os:
  - linux
  # python is not supported in osx build environment
  # python is not supported in windows build environment
python:
  - "3.6"
  - "3.7"
  - "3.8"
install: pip install tox-travis codecov
script: tox
after_success: codecov
